#---------------------------------------------------------------------------------
# Clear the implicit built in rules
#---------------------------------------------------------------------------------
.SUFFIXES:
#---------------------------------------------------------------------------------
ifeq ($(strip $(DEVKITPPC)),)
$(error "Please set DEVKITPPC in your environment. export DEVKITPPC=<path to>devkitPPC")
endif

include $(DEVKITPPC)/wii_rules

#---------------------------------------------------------------------------------
# TARGET is the name of the output
# BUILD is the directory where object files & intermediate files will be placed
# SOURCES is a list of directories containing source code
# INCLUDES is a list of directories containing extra header files
#---------------------------------------------------------------------------------
TARGET		:=	fbzx
BUILD		:=	build
SOURCES		:=	src src/z80free src/minizip src/tinyFTP src/rzx_lib
DATA		:=	 
INCLUDES	:=	

#---------------------------------------------------------------------------------
# options for code generation
#---------------------------------------------------------------------------------

CFLAGS	= -g -O3 -Wall -Wno-unused-but-set-variable $(MACHDEP) $(INCLUDE) -Wno-pointer-sign
CXXFLAGS	=	$(CFLAGS)

LDFLAGS	=	-g $(MACHDEP) -Wl,-Map,$(notdir $@).map

#---------------------------------------------------------------------------------
# any extra libraries we wish to link with the project
#---------------------------------------------------------------------------------
LIBS	:=	 -lasnd -lSDL_mixer -lsmpeg -lvorbisidec -lSDL_image -lpng -ljpeg -lz -lSDL_ttf -lSDL -lSDL_gfx -lfreetype -lfat -lwiiuse -lbte -logc -lm -lwiikeyboard -ltinysmb

#---------------------------------------------------------------------------------
# list of directories containing libraries, this must be the top level containing
# include and lib
#---------------------------------------------------------------------------------
LIBDIRS	:= $(PORTLIBS)


#---------------------------------------------------------------------------------
# no real need to edit anything past this point unless you need to add additional
# rules for different file extensions
#---------------------------------------------------------------------------------
ifneq ($(BUILD),$(notdir $(CURDIR)))
#---------------------------------------------------------------------------------

export OUTPUT	:=	$(CURDIR)/$(TARGET)

export VPATH	:=	$(foreach dir,$(SOURCES),$(CURDIR)/$(dir)) \
					$(foreach dir,$(DATA),$(CURDIR)/$(dir))

export DEPSDIR	:=	$(CURDIR)/$(BUILD)

#---------------------------------------------------------------------------------
# automatically build a list of object files for our project
#---------------------------------------------------------------------------------
CFILES		:=	$(foreach dir,$(SOURCES),$(notdir $(wildcard $(dir)/*.c)))
CFILES 		:=  $(filter-out z80free_tester.c, $(CFILES))
CPPFILES	:=	$(foreach dir,$(SOURCES),$(notdir $(wildcard $(dir)/*.cpp)))
sFILES		:=	$(foreach dir,$(SOURCES),$(notdir $(wildcard $(dir)/*.s)))
SFILES		:=	$(foreach dir,$(SOURCES),$(notdir $(wildcard $(dir)/*.S)))
BINFILES	:=	$(foreach dir,$(DATA),$(notdir $(wildcard $(dir)/*.*)))

#---------------------------------------------------------------------------------
# use CXX for linking C++ projects, CC for standard C
#---------------------------------------------------------------------------------
ifeq ($(strip $(CPPFILES)),)
	export LD	:=	$(CC)
else
	export LD	:=	$(CXX)
endif

export OFILES	:=	$(addsuffix .o,$(BINFILES)) \
					$(CPPFILES:.cpp=.o) $(CFILES:.c=.o) \
					$(sFILES:.s=.o) $(SFILES:.S=.o)

#---------------------------------------------------------------------------------
# build a list of include paths
#---------------------------------------------------------------------------------
export INCLUDE	:=	$(foreach dir,$(INCLUDES), -iquote $(CURDIR)/$(dir)) \
					$(foreach dir,$(LIBDIRS),-I$(dir)/include) \
					-I$(CURDIR)/$(BUILD) \
					-I$(LIBOGC_INC)

#---------------------------------------------------------------------------------
# build a list of library paths
#---------------------------------------------------------------------------------
export LIBPATHS	:=	$(foreach dir,$(LIBDIRS),-L$(dir)/lib) \
					-L$(LIBOGC_LIB)

export OUTPUT	:=	$(CURDIR)/$(TARGET)
.PHONY: $(BUILD) clean

#---------------------------------------------------------------------------------
$(BUILD):
	@[ -d $@ ] || mkdir -p $@
	@make --no-print-directory -C $(BUILD) -f $(CURDIR)/Makefile.wii

#---------------------------------------------------------------------------------
clean:
	@echo clean ...
	@rm -fr $(BUILD) $(OUTPUT).elf $(OUTPUT).dol dist

#---------------------------------------------------------------------------------


dist: $(BUILD)
	rm -fr $@
	mkdir -p $@/apps/fbzx-wii
	mkdir -p $@/fbzx-wii/fbzx
	mkdir -p $@/fbzx-wii/spectrum-roms
	mkdir -p $@/fbzx-wii/tapes
	mkdir -p $@/fbzx-wii/snapshots
	mkdir -p $@/fbzx-wii/snapshots/rom-cartridges
	mkdir -p $@/fbzx-wii/microdrives
	mkdir -p $@/fbzx-wii/scr
	mkdir -p $@/fbzx-wii/scr2
	mkdir -p $@/fbzx-wii/configurations
	mkdir -p $@/fbzx-wii/poke
	mkdir -p $@/fbzx-wii/rzx
	mkdir -p $@/apps/fbzx-wii/doc
	mkdir -p $@/fbzx-wii/fbzx/allophones
	cp fbzx.dol $@/apps/fbzx-wii/boot.dol
	cp meta.xml $@/apps/fbzx-wii/meta.xml
	cp icon.png $@/apps/fbzx-wii/icon.png
	cp spectrum-roms/* $@/fbzx-wii/spectrum-roms
	cp images/keymap.bmp $@/fbzx-wii/fbzx
	cp images/Spectrum_keyboard.png $@/fbzx-wii/fbzx
	cp images/symbol_shift.png $@/fbzx-wii/fbzx
	cp images/caps_shift.png $@/fbzx-wii/fbzx
	cp images/Spectrum_keyboard_small.png $@/fbzx-wii/fbzx
	cp images/symbol_shift_small.png $@/fbzx-wii/fbzx
	cp images/caps_shift_small.png $@/fbzx-wii/fbzx
	cp images/ZXSpectrum48k.png $@/fbzx-wii/fbzx
	cp images/stripes.png $@/fbzx-wii/fbzx
	cp images/stripes_small.png $@/fbzx-wii/fbzx
	cp images/ZX_Spectrum.ttf $@/fbzx-wii/fbzx
	cp images/FreeMono.ttf $@/fbzx-wii/fbzx
	cp sound/menu_navigation_BE.raw $@/fbzx-wii/fbzx
	cp sound/select_BE.raw $@/fbzx-wii/fbzx
	cp sound/unselect_BE.raw $@/fbzx-wii/fbzx
	cp fbzx.net $@/fbzx-wii
	cp AMSTRAD CAPABILITIES COPYING FAQ README VERSIONS.wii $@/apps/fbzx-wii/doc
	cp allophones/*.* $@/fbzx-wii/fbzx/allophones
	touch $@/fbzx-wii/tapes/dummy
	touch $@/fbzx-wii/snapshots/dummy
	touch $@/fbzx-wii/snapshots/rom-cartridges/dummy
	touch $@/fbzx-wii/microdrives/dummy
	touch $@/fbzx-wii/scr/dummy
	touch $@/fbzx-wii/scr2/dummy
	touch $@/fbzx-wii/configurations/dummy
	touch $@/fbzx-wii/poke/dummy
	touch $@/fbzx-wii/rzx/dummy
	cd $@ && tar -czf ../fbzx-wii-vx-bin.tar.gz *

distsource:
	cd .. && cp -r fbzx-wii fbzx-wii-v
	cd ../fbzx-wii-v && find . -name ".svn" | xargs rm -rf
	cd .. && tar -czf fbzx-wii-v.tar.gz fbzx-wii-v
	cd .. && rm -fr fbzx-wii-v
	
	

#---------------------------------------------------------------------------------
run:
	wiiload $(TARGET).dol


#---------------------------------------------------------------------------------
else

DEPENDS	:=	$(OFILES:.o=.d)

#---------------------------------------------------------------------------------
# main targets
#---------------------------------------------------------------------------------
$(OUTPUT).dol: $(OUTPUT).elf
$(OUTPUT).elf: $(OFILES)

#---------------------------------------------------------------------------------
# This rule links in binary data with the .jpg extension
#---------------------------------------------------------------------------------
%.jpg.o	:	%.jpg
#---------------------------------------------------------------------------------
	@echo $(notdir $<)
	$(bin2o)

-include $(DEPENDS)

#---------------------------------------------------------------------------------
endif
#---------------------------------------------------------------------------------
